export default {
    MAPK_NOTIFICATION_AS_READ_BY_ID:'MAPK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATION_AS_READ:'MARK_ALL_NOTIFICATION_AS_READ',
    START_NOTIFICATION_POST:'START_NOTIFICATION_POST',
    FINISH_NOTIFICATION_POST:'FINISH_NOTIFICATION_POST',
    RECIVED_NOTIFICATIONS:'RECIVED_NOTIFICATIONS',
    START_LOGIIN:'START_LOGIIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED'
}